export const SCRIPT_FIXTURE_LINES = {
  episodeHeaderCn: '第1集',
  episodeHeaderCnAlt: '第一集',
  episodeHeaderEn: 'EP.1',
  episodeHeaderSeason: 'S01E01',
  sectionHeader: '梗概',
  sectionHeaderIndexed: '1、人物小传',
  sceneHeaderBasic: '1-1 上午 内 客厅',
  sceneHeaderAlt: '1－1A 夜 外 街道',
  characters: '出场人物：宋也、林晚',
  dialogue: '宋也：你为什么不说话？',
  dialogueWithDirection: '宋也：（低声）你为什么不说话？',
  dialogueWithAsciiParen: '林晚: (停顿) 我不知道。',
  action: '▲他低头点燃香烟。',
  actionWithSpace: '▲ 他低头点燃香烟。',
  audioEffect: '[音效：手机震动]',
  audioBgm: '[BGM：压抑的弦乐渐起]',
  audioAmbient: '[环境音：酒店大厅轻柔的背景音乐《春江花月夜》]',
  uiSystem: '[系统提示：任务已完成]',
  uiDanmaku: '[弹幕：这也太虐了]',
  uiInteraction: '[界面操作：点击提交按钮]',
  uiBanner: '[提示条：剩余时间 10 秒]',
  uiGiftEffect: '[礼物特效：满屏烟花]',
  bracketNoteSquare: '[未知标签：保留兜底]',
  bracketNoteFullwidth: '【特写：镜头推近眼睛】',
  plainText: '普通正文',
} as const

export const SCRIPT_FIXTURE_DOCUMENTS = {
  fullStructuredSample: [
    SCRIPT_FIXTURE_LINES.episodeHeaderCn,
    SCRIPT_FIXTURE_LINES.sectionHeader,
    SCRIPT_FIXTURE_LINES.sceneHeaderBasic,
    SCRIPT_FIXTURE_LINES.characters,
    SCRIPT_FIXTURE_LINES.dialogueWithDirection,
    SCRIPT_FIXTURE_LINES.action,
    SCRIPT_FIXTURE_LINES.audioEffect,
    SCRIPT_FIXTURE_LINES.audioBgm,
    SCRIPT_FIXTURE_LINES.uiSystem,
    SCRIPT_FIXTURE_LINES.bracketNoteSquare,
    SCRIPT_FIXTURE_LINES.bracketNoteFullwidth,
  ].join('\n'),
  bracketedEventsSample: [
    SCRIPT_FIXTURE_LINES.sceneHeaderBasic,
    SCRIPT_FIXTURE_LINES.audioAmbient,
    SCRIPT_FIXTURE_LINES.uiDanmaku,
  ].join('\n'),
} as const
